### ISSUE TITLE
Tracking issue for migrating to npm native workspace

### ISSUE THREAD

**Issue by NickCao** [UltimateHackingKeyboard/agent#1999]
Motivation: npm native workspace is the officially supported way of organizing monorepos. And the legacy lerna way of managing packages is being deprecated: https://lerna.js.org/docs/features/legacy-package-management

Tasks:
- [x] Update lerna to a version that supports npm workspace: https://github.com/UltimateHackingKeyboard/agent/pull/1975
- [x] Remove references to `node_modules` in test scripts: https://github.com/UltimateHackingKeyboard/agent/pull/1991
- [ ] Remove references to `node_modules` in `package.json` (namely in the clean commands): `lerna clean` covers most part of this
- [ ] Remove references to `node_modules` in `tsconfig.*.json`: They are in the `paths` field, does not seem to be required?
- [ ] Remove references to `node_modules` in `angular.json`: Failed attempt in https://github.com/UltimateHackingKeyboard/agent/pull/1973
- [ ] Remove references to `node_modules` in `packages/uhk-web/src/styles/_variables.scss`: The referenced folder does not even exist?
- [ ] Remove references to `node_modules` in `packages/uhk-agent/webpack.config.js`
- [ ] Remove references to `node_modules` in `packages/uhk-common/src/buffer.ts`
